GET  http://127.0.0.1:3000/api/companies
Content-Type: application/json;

###
GET http://127.0.0.1:3000/api
###
GET  http://127.0.0.1:3000/api/company/1

Content-Type: application/json

###
POST http://127.0.0.1:3000/api/add-company

content-type: application/json

{
    "name": 54,
    "location": "Nigeria",
    "employees": 125,
    "founder": "Fiyin Akinsiku",
    "year": 2020,
    "website": "www.tech2base.com"
}

###
DELETE http://127.0.0.1:3000/delete/28

content-type: application/json

###
PUT http://127.0.0.1:3000/update/21

content-type: application/json

{
    "num": 300
}